# site settings when running at localhost
title: 'Test Blog LocalHost'
url: "http://127.0.0.1:8080" # the base hostname & protocol for your site

#livereload: true     # You no longer need to include --livereload
#reload_port: 5678    # If you don't want to use the default port
